version: "3.8"
services:
  itmo-assistant-ref:
    build: ..
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - LLM_PROVIDER=${LLM_PROVIDER}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - MISTRAL_MODEL=${MISTRAL_MODEL}
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    command: bash -lc "python -m app.ingest && python -m app.search.index && python -m app.webapi"